### ISSUE TITLE
Submit to termux package management team

### ISSUE THREAD

**Issue by BlueDrink9** [aeolwyr/tergent#1]
This is a really neat program. Would love to see it installable through pkg.

**Comment by aeolwyr** [comment]
Thanks for the kind words! I did not have time to work on the project since the release, but I will get it to the official repositories as soon as I have a chance.

**Comment by BlueDrink9** [comment]
It's apparently already there! I just installed it, after downloading your release binary and trying to run it from the wrong directory. Congrats!
