### ISSUE TITLE
unlocking with fingerprint

### ISSUE THREAD

**Issue by inos-github** [aeolwyr/tergent#10]
For keys with validity set > 0 the unlocking is described in the README. However there is a possibility to unlock with fingerprint using the termux-fingerprint command as well:

`termux-fingerprint 1>/dev/null && ssh example.com`

To make things more easy you can set an alias in .bashrc or .zshrc

**Comment by aeolwyr** [comment]
Oh, I had no idea. Well my device doesn't have a fingerprint reader, but I was curious and I used another unrelated app that requires biometrics (face unlock), and as you said, it reset the timer. Neat.

I will update the README with this information, thanks for the tip!

**Comment by aeolwyr** [comment]
Added this information to README in d4b2566.
