### ISSUE TITLE
asking for PIN

### ISSUE THREAD

**Issue by micsuka** [aeolwyr/tergent#11]
thanks for developing this tergent library.
I would have a question, which is not really clear to me is that after I generated a RSA or EC key based on the README, the 
`ssh-keygen -D  $PREFIX/lib/libtergent.so`
is asking for a PIN:
`Enter PIN for 'tergent':
PKCS#11 login failed: error 84
login failed
cannot read public key from pkcs11`

maybe there are other users facing this problem...
so it's not clear to me that is the termux keystore involved in storing the key or not...

thanks

**Comment by aeolwyr** [comment]
Yeah that's definitely unexpected. There are a few things you can try to get more information:

1. The easiest is to run `ssh-keygen -v -D $PREFIX/lib/libtergent.so`.

2. Next up, you can try signing some data manually.
`echo test | termux-keystore sign myrsakey NONEwithRSA`
or
`echo test | termux-keystore sign myeckey NONEwithECDSA`
depending on your key type.
This should print some rubbish on the screen. If it prints nothing, the key is not working properly.

3. Finally, if these don't tell us much, pkcs11-spy in [OpenSC project](https://github.com/OpenSC/OpenSC) provides very detailed report of the communication. Unfortunately OpenSC is not available in the official repositories, you can build it manually or [download the one](https://github.com/aeolwyr/tergent/files/5066932/pkcs11-spy.so.tar.gz) file I have been using for testing. Assuming you placed the file in your home directory, you can run
`PKCS11SPY=$PREFIX/lib/libtergent.so ssh-keygen -D $HOME/pkcs11-spy.so`
which will provide lots of useful information we can use for diagnosing.

**Comment by micsuka** [comment]
sorry, it was my fault, I made a mistake when I generated the key. the 1.0.0 works properly :)
thank you for your time and your work.
