### ISSUE TITLE
Include arm binary in releases?

### ISSUE THREAD

**Issue by BlueDrink9** [aeolwyr/tergent#2]
Would love to use this, but haven't been able to build it myself. Would you mind compiling an arm release?

**Comment by aeolwyr** [comment]
According to [this page](https://forge.rust-lang.org/platform-support.html), both ARMv7 and ARMv7a builds are possible. I am not sure about the differences between them, which one do you need?

**Comment by BlueDrink9** [comment]
Good question. Assuming others will want them, why not add both? Is it a long compile-time?

**Comment by aeolwyr** [comment]
The main issues are testing and setting up the NDK and build tools etc. In my case it seems that the tools I have do not support ARMv7, particularly `make_standalone_toolchain.py`.

I was able to build for ARMv7a, and attached that to the release (named `tergent_0.1.1-1_armv7-linux-androideabi.tar.gz`).

I already had the ARM64 build, which I hoped would cover most recent phones, though I will build for ARMv7a going forward. That being said, my device is ARM64 so I can't test it outside of an emulator. I hope it works.
