### ISSUE TITLE
agent refused operation

### ISSUE THREAD

**Issue by 532910** [aeolwyr/tergent#8]
```
% eval $(tergent)
Agent pid 20638
% ssh-add .ssh/id_ed25519
Enter passphrase for .ssh/id_ed25519:
Could not add identity ".ssh/id_ed25519": agent refused operation
zsh: exit 1     ssh-add .ssh/id_ed25519
```

**Comment by aeolwyr** [comment]
Hello, this is one of the issues presented by #4. Tergent incorrectly presented itself as an ssh-agent. The use case you are mentioning here (adding an external key) was not supported.

Well, it is still not supported, but at least [release 1.0](https://github.com/aeolwyr/tergent/releases/tag/1.0.0) stops advertising itself as an ssh-agent. This also means you can use the regular `ssh-agent` and tergent at the same time now.

Please note that if you wish to upgrade, you will need to follow the README as you'll need to regenerate the keys stored in Termux keystore. The keys stored in your file system are not affected.
